const timezoneData = [
    { city: "New York City", country: "USA", timezone: "America/New_York", abbr: "EST/EDT" },
    { city: "Los Angeles", country: "USA", timezone: "America/Los_Angeles", abbr: "PST/PDT" },
    { city: "Chicago", country: "USA", timezone: "America/Chicago", abbr: "CST/CDT" },
    { city: "Denver", country: "USA", timezone: "America/Denver", abbr: "MST/MDT" },
    { city: "Phoenix", country: "USA", timezone: "America/Phoenix", abbr: "MST" },
    { city: "Houston", country: "USA", timezone: "America/Chicago", abbr: "CST/CDT" },
    { city: "Miami", country: "USA", timezone: "America/New_York", abbr: "EST/EDT" },
    { city: "Seattle", country: "USA", timezone: "America/Los_Angeles", abbr: "PST/PDT" },
    { city: "Boston", country: "USA", timezone: "America/New_York", abbr: "EST/EDT" },
    { city: "San Francisco", country: "USA", timezone: "America/Los_Angeles", abbr: "PST/PDT" },
    { city: "Las Vegas", country: "USA", timezone: "America/Los_Angeles", abbr: "PST/PDT" },
    { city: "Atlanta", country: "USA", timezone: "America/New_York", abbr: "EST/EDT" },
    { city: "Dallas", country: "USA", timezone: "America/Chicago", abbr: "CST/CDT" },
    { city: "Honolulu", country: "USA", timezone: "Pacific/Honolulu", abbr: "HST" },
    { city: "Anchorage", country: "USA", timezone: "America/Anchorage", abbr: "AKST/AKDT" },

    { city: "London", country: "UK", timezone: "Europe/London", abbr: "GMT/BST" },
    { city: "Paris", country: "France", timezone: "Europe/Paris", abbr: "CET/CEST" },
    { city: "Berlin", country: "Germany", timezone: "Europe/Berlin", abbr: "CET/CEST" },
    { city: "Madrid", country: "Spain", timezone: "Europe/Madrid", abbr: "CET/CEST" },
    { city: "Rome", country: "Italy", timezone: "Europe/Rome", abbr: "CET/CEST" },
    { city: "Amsterdam", country: "Netherlands", timezone: "Europe/Amsterdam", abbr: "CET/CEST" },
    { city: "Brussels", country: "Belgium", timezone: "Europe/Brussels", abbr: "CET/CEST" },
    { city: "Vienna", country: "Austria", timezone: "Europe/Vienna", abbr: "CET/CEST" },
    { city: "Prague", country: "Czech Republic", timezone: "Europe/Prague", abbr: "CET/CEST" },
    { city: "Stockholm", country: "Sweden", timezone: "Europe/Stockholm", abbr: "CET/CEST" },
    { city: "Copenhagen", country: "Denmark", timezone: "Europe/Copenhagen", abbr: "CET/CEST" },
    { city: "Oslo", country: "Norway", timezone: "Europe/Oslo", abbr: "CET/CEST" },
    { city: "Helsinki", country: "Finland", timezone: "Europe/Helsinki", abbr: "EET/EEST" },
    { city: "Athens", country: "Greece", timezone: "Europe/Athens", abbr: "EET/EEST" },
    { city: "Warsaw", country: "Poland", timezone: "Europe/Warsaw", abbr: "CET/CEST" },
    { city: "Budapest", country: "Hungary", timezone: "Europe/Budapest", abbr: "CET/CEST" },
    { city: "Lisbon", country: "Portugal", timezone: "Europe/Lisbon", abbr: "WET/WEST" },
    { city: "Dublin", country: "Ireland", timezone: "Europe/Dublin", abbr: "GMT/IST" },
    { city: "Edinburgh", country: "UK", timezone: "Europe/London", abbr: "GMT/BST" },
    { city: "Manchester", country: "UK", timezone: "Europe/London", abbr: "GMT/BST" },
    { city: "Barcelona", country: "Spain", timezone: "Europe/Madrid", abbr: "CET/CEST" },
    { city: "Munich", country: "Germany", timezone: "Europe/Berlin", abbr: "CET/CEST" },
    { city: "Milan", country: "Italy", timezone: "Europe/Rome", abbr: "CET/CEST" },
    { city: "Zurich", country: "Switzerland", timezone: "Europe/Zurich", abbr: "CET/CEST" },
    { city: "Geneva", country: "Switzerland", timezone: "Europe/Zurich", abbr: "CET/CEST" },

    { city: "Moscow", country: "Russia", timezone: "Europe/Moscow", abbr: "MSK" },
    { city: "Istanbul", country: "Turkey", timezone: "Europe/Istanbul", abbr: "TRT" },
    { city: "Dubai", country: "UAE", timezone: "Asia/Dubai", abbr: "GST" },
    { city: "Mumbai", country: "India", timezone: "Asia/Kolkata", abbr: "IST" },
    { city: "New Delhi", country: "India", timezone: "Asia/Kolkata", abbr: "IST" },
    { city: "Bangalore", country: "India", timezone: "Asia/Kolkata", abbr: "IST" },
    { city: "Kolkata", country: "India", timezone: "Asia/Kolkata", abbr: "IST" },
    { city: "Bangkok", country: "Thailand", timezone: "Asia/Bangkok", abbr: "ICT" },
    { city: "Singapore", country: "Singapore", timezone: "Asia/Singapore", abbr: "SGT" },
    { city: "Hong Kong", country: "China", timezone: "Asia/Hong_Kong", abbr: "HKT" },
    { city: "Beijing", country: "China", timezone: "Asia/Shanghai", abbr: "CST" },
    { city: "Shanghai", country: "China", timezone: "Asia/Shanghai", abbr: "CST" },
    { city: "Tokyo", country: "Japan", timezone: "Asia/Tokyo", abbr: "JST" },
    { city: "Osaka", country: "Japan", timezone: "Asia/Tokyo", abbr: "JST" },
    { city: "Kyoto", country: "Japan", timezone: "Asia/Tokyo", abbr: "JST" },
    { city: "Seoul", country: "South Korea", timezone: "Asia/Seoul", abbr: "KST" },
    { city: "Taipei", country: "Taiwan", timezone: "Asia/Taipei", abbr: "CST" },
    { city: "Manila", country: "Philippines", timezone: "Asia/Manila", abbr: "PHT" },
    { city: "Jakarta", country: "Indonesia", timezone: "Asia/Jakarta", abbr: "WIB" },
    { city: "Kuala Lumpur", country: "Malaysia", timezone: "Asia/Kuala_Lumpur", abbr: "MYT" },
    { city: "Ho Chi Minh City", country: "Vietnam", timezone: "Asia/Ho_Chi_Minh", abbr: "ICT" },
    { city: "Hanoi", country: "Vietnam", timezone: "Asia/Ho_Chi_Minh", abbr: "ICT" },

    { city: "Sydney", country: "Australia", timezone: "Australia/Sydney", abbr: "AEDT/AEST" },
    { city: "Melbourne", country: "Australia", timezone: "Australia/Melbourne", abbr: "AEDT/AEST" },
    { city: "Brisbane", country: "Australia", timezone: "Australia/Brisbane", abbr: "AEST" },
    { city: "Perth", country: "Australia", timezone: "Australia/Perth", abbr: "AWST" },
    { city: "Adelaide", country: "Australia", timezone: "Australia/Adelaide", abbr: "ACDT/ACST" },
    { city: "Auckland", country: "New Zealand", timezone: "Pacific/Auckland", abbr: "NZDT/NZST" },
    { city: "Wellington", country: "New Zealand", timezone: "Pacific/Auckland", abbr: "NZDT/NZST" },

    { city: "Toronto", country: "Canada", timezone: "America/Toronto", abbr: "EST/EDT" },
    { city: "Vancouver", country: "Canada", timezone: "America/Vancouver", abbr: "PST/PDT" },
    { city: "Montreal", country: "Canada", timezone: "America/Toronto", abbr: "EST/EDT" },
    { city: "Calgary", country: "Canada", timezone: "America/Edmonton", abbr: "MST/MDT" },
    { city: "Ottawa", country: "Canada", timezone: "America/Toronto", abbr: "EST/EDT" },
    { city: "Edmonton", country: "Canada", timezone: "America/Edmonton", abbr: "MST/MDT" },
    { city: "Quebec City", country: "Canada", timezone: "America/Toronto", abbr: "EST/EDT" },
    { city: "Winnipeg", country: "Canada", timezone: "America/Winnipeg", abbr: "CST/CDT" },
    { city: "Halifax", country: "Canada", timezone: "America/Halifax", abbr: "AST/ADT" },

    { city: "Mexico City", country: "Mexico", timezone: "America/Mexico_City", abbr: "CST/CDT" },
    { city: "Guadalajara", country: "Mexico", timezone: "America/Mexico_City", abbr: "CST/CDT" },
    { city: "Monterrey", country: "Mexico", timezone: "America/Monterrey", abbr: "CST/CDT" },
    { city: "Cancun", country: "Mexico", timezone: "America/Cancun", abbr: "EST" },
    { city: "Tijuana", country: "Mexico", timezone: "America/Tijuana", abbr: "PST/PDT" },

    { city: "São Paulo", country: "Brazil", timezone: "America/Sao_Paulo", abbr: "BRT/BRST" },
    { city: "Rio de Janeiro", country: "Brazil", timezone: "America/Sao_Paulo", abbr: "BRT/BRST" },
    { city: "Buenos Aires", country: "Argentina", timezone: "America/Argentina/Buenos_Aires", abbr: "ART" },
    { city: "Santiago", country: "Chile", timezone: "America/Santiago", abbr: "CLT/CLST" },
    { city: "Lima", country: "Peru", timezone: "America/Lima", abbr: "PET" },
    { city: "Bogotá", country: "Colombia", timezone: "America/Bogota", abbr: "COT" },
    { city: "Caracas", country: "Venezuela", timezone: "America/Caracas", abbr: "VET" },
    { city: "Quito", country: "Ecuador", timezone: "America/Guayaquil", abbr: "ECT" },

    { city: "Cairo", country: "Egypt", timezone: "Africa/Cairo", abbr: "EET" },
    { city: "Lagos", country: "Nigeria", timezone: "Africa/Lagos", abbr: "WAT" },
    { city: "Johannesburg", country: "South Africa", timezone: "Africa/Johannesburg", abbr: "SAST" },
    { city: "Cape Town", country: "South Africa", timezone: "Africa/Johannesburg", abbr: "SAST" },
    { city: "Nairobi", country: "Kenya", timezone: "Africa/Nairobi", abbr: "EAT" },
    { city: "Casablanca", country: "Morocco", timezone: "Africa/Casablanca", abbr: "WET/WEST" },
    { city: "Algiers", country: "Algeria", timezone: "Africa/Algiers", abbr: "CET" },
    { city: "Addis Ababa", country: "Ethiopia", timezone: "Africa/Addis_Ababa", abbr: "EAT" },
    { city: "Accra", country: "Ghana", timezone: "Africa/Accra", abbr: "GMT" },

    { city: "Tel Aviv", country: "Israel", timezone: "Asia/Jerusalem", abbr: "IST/IDT" },
    { city: "Jerusalem", country: "Israel", timezone: "Asia/Jerusalem", abbr: "IST/IDT" },
    { city: "Riyadh", country: "Saudi Arabia", timezone: "Asia/Riyadh", abbr: "AST" },
    { city: "Kuwait City", country: "Kuwait", timezone: "Asia/Kuwait", abbr: "AST" },
    { city: "Doha", country: "Qatar", timezone: "Asia/Qatar", abbr: "AST" },
    { city: "Abu Dhabi", country: "UAE", timezone: "Asia/Dubai", abbr: "GST" },
    { city: "Amman", country: "Jordan", timezone: "Asia/Amman", abbr: "EET/EEST" },
    { city: "Beirut", country: "Lebanon", timezone: "Asia/Beirut", abbr: "EET/EEST" },
    { city: "Damascus", country: "Syria", timezone: "Asia/Damascus", abbr: "EET/EEST" },
    { city: "Baghdad", country: "Iraq", timezone: "Asia/Baghdad", abbr: "AST" },
    { city: "Tehran", country: "Iran", timezone: "Asia/Tehran", abbr: "IRST/IRDT" },

    { city: "Karachi", country: "Pakistan", timezone: "Asia/Karachi", abbr: "PKT" },
    { city: "Islamabad", country: "Pakistan", timezone: "Asia/Karachi", abbr: "PKT" },
    { city: "Lahore", country: "Pakistan", timezone: "Asia/Karachi", abbr: "PKT" },
    { city: "Dhaka", country: "Bangladesh", timezone: "Asia/Dhaka", abbr: "BST" },
    { city: "Colombo", country: "Sri Lanka", timezone: "Asia/Colombo", abbr: "IST" },
    { city: "Kathmandu", country: "Nepal", timezone: "Asia/Kathmandu", abbr: "NPT" },
    { city: "Tashkent", country: "Uzbekistan", timezone: "Asia/Tashkent", abbr: "UZT" },
    { city: "Almaty", country: "Kazakhstan", timezone: "Asia/Almaty", abbr: "ALMT" },
    { city: "Astana", country: "Kazakhstan", timezone: "Asia/Almaty", abbr: "ALMT" },

    { city: "Reykjavik", country: "Iceland", timezone: "Atlantic/Reykjavik", abbr: "GMT" },
    { city: "Fiji", country: "Fiji", timezone: "Pacific/Fiji", abbr: "FJT/FJST" },
    { city: "Port Moresby", country: "Papua New Guinea", timezone: "Pacific/Port_Moresby", abbr: "PGT" }
];